# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_incident_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='deviceid',
            field=models.CharField(default=12345, max_length=50),
            preserve_default=False,
        ),
    ]
