# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_incident_deviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='longitude',
            field=models.CharField(max_length=50),
        ),
    ]
