# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Safeplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('suburb', models.CharField(max_length=250)),
                ('postcode', models.IntegerField()),
                ('state', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
