# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 15:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailtrack', '0002_auto_20170429_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailtrack',
            name='latitude',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='trailtrack',
            name='longitude',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
