# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailtrack', '0005_auto_20170501_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailtrack',
            name='battery_status',
            field=models.CharField(default='50%', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailtrack',
            name='first_name',
            field=models.CharField(default='Phurich', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailtrack',
            name='last_name',
            field=models.CharField(default='Pusapanich', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailtrack',
            name='user_phone_number',
            field=models.CharField(default=61452585390, max_length=50),
            preserve_default=False,
        ),
    ]
