# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailtrack', '0006_auto_20170505_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trailtrack',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='trailtrack',
            name='battery_status',
        ),
        migrations.RemoveField(
            model_name='trailtrack',
            name='last_name',
        ),
    ]
